<a href="https://colab.research.google.com/github/adity1997/pytorch_tutorial/blob/main/My_first_pytorch_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch fundamentals course

* Link to the [course content](https://www.learnpytorch.io/)
* Link to Pytorch documentation [pytorch docs](https://pytorch.org/docs/stable/index.html)

In [1]:
import torch

In [2]:
print(torch.__version__)

2.1.0+cu118


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([7,7])

In [8]:
vector

tensor([7, 7])

In [9]:
MATRIX = torch.tensor([[7,8],[9,10]])

In [10]:
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
type(MATRIX.shape)

torch.Size

In [14]:
type(MATRIX)

torch.Tensor

In [15]:
TENSOR = torch.tensor([[[1,2,3],[1,11,11],[1,24,4]]])

In [16]:
TENSOR

tensor([[[ 1,  2,  3],
         [ 1, 11, 11],
         [ 1, 24,  4]]])

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
#Creating random tensors
RANDOM_TENSOR = torch.rand(11,11,11,10,5,6)

In [19]:
RANDOM_TENSOR

tensor([[[[[[8.5083e-01, 8.4388e-01, 6.0169e-01, 5.7947e-01, 1.1794e-01,
             9.4242e-01],
            [3.5971e-01, 3.8393e-01, 9.7348e-01, 2.1333e-01, 7.0917e-01,
             3.3195e-02],
            [4.2485e-01, 9.9242e-01, 9.2465e-01, 4.0082e-02, 2.5070e-01,
             2.5227e-01],
            [9.7028e-01, 7.1693e-01, 8.8149e-01, 9.1662e-01, 5.4108e-01,
             9.2465e-02],
            [8.0099e-01, 2.8685e-01, 4.0112e-01, 7.9918e-01, 7.7734e-01,
             3.9780e-01]],

           [[6.5230e-01, 6.5436e-01, 5.0747e-01, 8.3777e-01, 3.3203e-01,
             9.9522e-02],
            [4.7781e-01, 5.8107e-01, 7.6413e-01, 3.5139e-01, 1.0136e-03,
             6.3505e-01],
            [1.1075e-01, 6.3936e-01, 9.7461e-01, 5.2888e-01, 1.0837e-01,
             5.5564e-01],
            [5.5915e-01, 5.7823e-01, 1.7575e-01, 2.5896e-01, 4.8731e-01,
             6.0350e-01],
            [2.3614e-01, 8.5657e-01, 2.0736e-01, 6.8636e-01, 8.7402e-01,
             1.7645e-02]],

      

In [20]:
RANDOM_TENSOR.ndim

6

In [21]:
x = torch.arange(0,100,10)

In [22]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
x.argmin()

tensor(0)

In [24]:
x.argmax()

tensor(9)

In [25]:
x.type(torch.float32).mean()

tensor(45.)

In [26]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [27]:
torch.stack([x,x,x])

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [28]:
torch.stack([x,x,x],dim=1)

tensor([[ 0,  0,  0],
        [10, 10, 10],
        [20, 20, 20],
        [30, 30, 30],
        [40, 40, 40],
        [50, 50, 50],
        [60, 60, 60],
        [70, 70, 70],
        [80, 80, 80],
        [90, 90, 90]])

In [29]:
a = torch.rand(1,44)

In [30]:
a.ndim

2

In [31]:
temp = torch.stack([a,a])

In [32]:
temp,temp.shape

(tensor([[[0.5805, 0.5692, 0.0848, 0.0298, 0.9067, 0.7976, 0.6437, 0.2577,
           0.6625, 0.6039, 0.8117, 0.8280, 0.2511, 0.4433, 0.8643, 0.7115,
           0.7530, 0.2614, 0.5018, 0.2527, 0.6121, 0.5435, 0.2039, 0.1611,
           0.6665, 0.6571, 0.2628, 0.1140, 0.4325, 0.6655, 0.4500, 0.9227,
           0.3935, 0.1493, 0.3217, 0.6183, 0.3379, 0.5709, 0.4297, 0.3802,
           0.0965, 0.8831, 0.3715, 0.8768]],
 
         [[0.5805, 0.5692, 0.0848, 0.0298, 0.9067, 0.7976, 0.6437, 0.2577,
           0.6625, 0.6039, 0.8117, 0.8280, 0.2511, 0.4433, 0.8643, 0.7115,
           0.7530, 0.2614, 0.5018, 0.2527, 0.6121, 0.5435, 0.2039, 0.1611,
           0.6665, 0.6571, 0.2628, 0.1140, 0.4325, 0.6655, 0.4500, 0.9227,
           0.3935, 0.1493, 0.3217, 0.6183, 0.3379, 0.5709, 0.4297, 0.3802,
           0.0965, 0.8831, 0.3715, 0.8768]]]),
 torch.Size([2, 1, 44]))

In [33]:
tep_1= torch.vstack([a,a])

In [34]:
tep_1

tensor([[0.5805, 0.5692, 0.0848, 0.0298, 0.9067, 0.7976, 0.6437, 0.2577, 0.6625,
         0.6039, 0.8117, 0.8280, 0.2511, 0.4433, 0.8643, 0.7115, 0.7530, 0.2614,
         0.5018, 0.2527, 0.6121, 0.5435, 0.2039, 0.1611, 0.6665, 0.6571, 0.2628,
         0.1140, 0.4325, 0.6655, 0.4500, 0.9227, 0.3935, 0.1493, 0.3217, 0.6183,
         0.3379, 0.5709, 0.4297, 0.3802, 0.0965, 0.8831, 0.3715, 0.8768],
        [0.5805, 0.5692, 0.0848, 0.0298, 0.9067, 0.7976, 0.6437, 0.2577, 0.6625,
         0.6039, 0.8117, 0.8280, 0.2511, 0.4433, 0.8643, 0.7115, 0.7530, 0.2614,
         0.5018, 0.2527, 0.6121, 0.5435, 0.2039, 0.1611, 0.6665, 0.6571, 0.2628,
         0.1140, 0.4325, 0.6655, 0.4500, 0.9227, 0.3935, 0.1493, 0.3217, 0.6183,
         0.3379, 0.5709, 0.4297, 0.3802, 0.0965, 0.8831, 0.3715, 0.8768]])

In [35]:
tep_2= torch.hstack([a,a])

In [36]:
tep_2.shape

torch.Size([1, 88])

In [37]:
tep_1.shape

torch.Size([2, 44])

#Squeezing and unspeezing


In [38]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()
y = torch.squeeze(x)
y.size()
y = torch.squeeze(x, 0)
y.size()
y = torch.squeeze(x, 1)
y.size()
y = torch.squeeze(x, (1, 2, 3))


In [39]:
x,x.shape

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [40]:
y,y.shape

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

In [41]:
tep_2.shape

torch.Size([1, 88])

In [42]:
a = torch.arange(1.,10.)

In [43]:
a.shape

torch.Size([9])

In [44]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [45]:
x.shape

torch.Size([2, 1, 2, 1, 2])

In [46]:
b= torch.unsqueeze(a,dim=0)

In [47]:
b.shape

torch.Size([1, 9])

In [48]:
c = torch.unsqueeze(b,dim=0)
d = torch.unsqueeze(b,dim=1)
e = torch.unsqueeze(b,dim=2)

In [49]:
b.shape,c.shape,d.shape,e.shape

(torch.Size([1, 9]),
 torch.Size([1, 1, 9]),
 torch.Size([1, 1, 9]),
 torch.Size([1, 9, 1]))

In [50]:
# torch.permute rearrranges the target tensor dimension specified dimensions

In [51]:
x_org = torch.rand(size=(224,224,3)) #[height,width,color_channel]
x_permute = torch.permute(x_org,dims=(2,0,1)) # Changes the position of axis/dim

In [52]:
x_org.shape,x_permute.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [53]:
x_org[0,0,0] = 8888

In [54]:
x_permute[0,0,0]

tensor(8888.)

# INDEXING

Indexing is similar to indexing in numpy

In [55]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [56]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [57]:
x[0][2][2]

tensor(9)

In [58]:
x[:,2,2]

tensor([9])

In [59]:
x,x[:,1,1]

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([5]))

In [60]:
x,x[:,:,2]

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([[3, 6, 9]]))

In [61]:
x[0,0,:]

tensor([1, 2, 3])

Numpy from pytorch.
torch.from_numpy(ndarray)
torch.Tensor.numpy()

In [62]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
# Default numpy dtype is float 64 and default dtype for torch tensor is float 32
# Just keep in mind while using pytorch
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [63]:
type(array)

numpy.ndarray

In [64]:
# Tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

In [65]:
numpy_tensor

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

## Reproducibilty(trying out to take random out of randomness)

* In short how nn learns.

* start with random number tensor operations update random number to try and make them better representations of data again again and again
* To reduce the randomness in nn and Pytorch comes the concepyt of **random seed**.
* Essentially what random seed does is ***flavor*** randomness

* Link for reproducibilty documentation in Pytorch [link text](https://pytorch.org/docs/stable/notes/randomness.html)

* Link for random seed generation in numpy documentation [link text](https://numpy.org/doc/stable/reference/random/generated/numpy.random.seed.html)

In [66]:
import torch
rand_tensor_A = torch.rand(3,4)
rand_tensor_B = torch.rand(3,4)

print(rand_tensor_A)
print(rand_tensor_B)
print(rand_tensor_A == rand_tensor_B)

tensor([[0.7675, 0.9292, 0.1221, 0.5123],
        [0.4299, 0.5320, 0.2459, 0.3697],
        [0.2883, 0.4840, 0.1958, 0.5358]])
tensor([[0.0365, 0.0631, 0.8588, 0.3441],
        [0.5427, 0.3426, 0.7902, 0.5586],
        [0.3900, 0.9834, 0.3767, 0.4418]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [67]:
import torch

# Set random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
rand_tensor_C = torch.rand(3,4)

# Need to set the random seed before every use of rand argument
torch.manual_seed(RANDOM_SEED)
rand_tensor_D = torch.rand(3,4)


print(rand_tensor_C)
print(rand_tensor_D)
print(rand_tensor_C == rand_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### **Running tensor and pytorch objects on GPUs**

* Getting GPU
* Use google colab for it, maybe google colab pro not need now
  for free version might need to wait for someone to finish coding

* Using physical GPU
* Also available on cloud platform AWS, Azure, etc..
* Google Colab is enough for now
* Cuda semantics [link text](https://pytorch.org/docs/stable/ notes/cuda.html)

In [68]:
!nvidia-smi

Sun Nov 26 13:48:08 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [69]:
# Check for GPU access in pytorch
import torch
torch.cuda.is_available()

True

In [70]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [71]:
# Count number of GPU
torch.cuda.device_count()

1

In [72]:
import torch
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [73]:
# Move tensor on GPU
tensor_on_GPU = tensor.to(device)
tensor_on_GPU

tensor([1, 2, 3], device='cuda:0')

### 4. Move tensor back to the CPU

In [74]:
tensor_on_GPU.numpy()

TypeError: ignored

In [75]:
tensor_on_CPU = tensor_on_GPU.cpu().numpy()
tensor_on_CPU

array([1, 2, 3])

In [76]:
tensor_on_GPU

tensor([1, 2, 3], device='cuda:0')